# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Carlos Ré
title: Software Engineer
email: carlos.santos.re@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  cfcfs
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: carlosre
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Hackerrank
  icon: fas fa-globe
  url: https://www.hackerrank.com/cfcfs
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Carlos and I'm a software engineer. I've accumulated some experience in building scalable and resilient systems, from architecture to development and operations. 

  I have also experience in leading teams, setting up processes and developing a healthy engineering culture.


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: mercedes-benz.io
        link: mercedes-benz.io
        quote: >
          Building a global digital marketing and sales channel for Mercedes-Benz
        description: | # this will include new lines to allow paragraphs
          <br/>

          ## May 2021 - Present | Head of Engineering
          Working on the recruitment, enablement and practices definition of technical roles  

          <br/>

          ## Jan 2020 - May 2021 | Program Tech Lead
          Worked, as a member of the architecture board, in defining a target architecture to allow unifying and scaling the marketing and sales platforms  
          Supported the recruitment process for tech roles and the definition of new roles

          <br/>

          ## Jan 2019 - Dec 2019 | Software Architect
          Designed the architecture and supported the implementation of a vehicle overview component included in the landing page of all Mercedes-Benz websites  
          Enabled the adoption of new practices for microservices development in several products, eg Kotlin as the core language, reactive patterns, trunk based development  


          <br/>

          ## Sep 2017 - Dec 2018 | Software Engineer
          Refactored a central data microservice to allow rule based configurations, highly reducing the amount of maintenance work and time to reflect upstream changes  


      - layout: left
        title: Caixa Geral de Depósitos
        link: cgd.pt
        quote: >
          Developing and operating of a highly available, mission critical integration layer around core bank systems
        description: | # this will include new lines to allow paragraphs
          <br/>

          ## Jan 2011 - Sep 2017 | Team Manager
          Refactored development and CI/CD toolchain for the Integration team using maven, nexus, jenkins and gitlab  
          Built a configuration management pipeline using git, ansible and wsadmin to allow a reproduceable and consistent infra-structure  
          Built a deployment pipeline to allow blue-green deployments, highly increasing the frequency of deployments  
          Steered the creation of a provisioning portal for integration services, while automating some of the boilerplate tasks, using django, angular and x3270  
          Replaced legacy code generation tool for mainframe based services to improve maintainability, using antlr, python and jinja2  

          <br/>

          ## Oct 2003 - Dec 2010 | Software Engineer
          Worked as part of the Integration team in designing and developing a SOA middleware platform supporting business applications (home banking, mobile apps, front office), based on JEE and WebServices  
          Developed code generation tools for legacy systems (CICS, SAP/R3) JCA access  
          Led the transformation (refactoring, development methodologies, team setup) of a BPM Platform with critical stability and maintainability issues, allowing new processes to be developed on top  

      - layout: left
        title: Link Consulting
        link: link.pt
        description: | # this will include new lines to allow paragraphs
          ## Apr 2001 - Oct 2003 | Consultant
          Development of B2B marketplaces, extending base Ariba (JEE based) funcionalities  
          Migration of some vodafone.pt portals (Vizzavi, Yorn) - Vignette, Oracle, Solaris  
          Designed and bootstrapped development of urban travel ticket management project for Otlis (transport operators consortium)  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Instituto Superior Técnico, Lisbon
        caption: 1995-2001
        description: | # this will include new lines to allow paragraphs
          M.Sc. Information Systems and Computer Engineering

  - title: Tech Stack
    layout: text
    content: | # this will include new lines to allow paragraphs
      Kotlin, Java, Python, C, Kubernetes, Cloud Foundry, Docker, AWS

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
